### ISSUE TITLE
Add function_id parameters for `spec-file`

### ISSUE THREAD

**Issue by ildar-gilmanov** [yc-actions/yc-api-gateway-deploy#283]
In API Gateway we may use Yandex Cloud functions like this:

```yaml
paths:
  my-path:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: <ID of previously uploaded Yandex Cloud Function>
```

So, we can get the `function_id` from previously called `yc-actions/yc-sls-function@v2` GitHub Action, but we cannot push it to the [yc-api-gateway-deploy](https://github.com/yc-actions/yc-api-gateway-deploy) GitHub Action. Yes, we can use `spec` property instead of `spec-file`,  but it is not a suitable way for big OpenAPI specifications.

Also please note that the OpenAPI specification file can contain many function IDs. So, I see the two ways to do the task:

1. Use placeholders into OpenAPI file, like this: `function_id: MY_FUNCTION_ID`
2. Or use paths. In this case in `yc-api-gateway-deploy` the function IDs may be provided like this: `my-path/post/function_id: dsfasdfsafasfs`
